# Generated by Django 4.1.7 on 2023-04-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0004_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('token', models.IntegerField()),
                ('date', models.DateField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
