# Generated by Django 4.1.7 on 2023-04-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0006_booking_hospital_booking_doctor_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Hospital',
        ),
    ]
