# Generated by Django 4.1.7 on 2023-04-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0007_remove_booking_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Address',
            new_name='address',
        ),
    ]
