# Generated by Django 4.1.7 on 2023-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0008_rename_address_booking_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token',
            field=models.CharField(max_length=2),
        ),
    ]
