# Generated by Django 4.1.7 on 2023-04-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0010_alter_booking_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='muncipality',
        ),
    ]
