# Generated by Django 4.1.7 on 2023-04-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0012_booking_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
    ]
