# Generated by Django 4.1.7 on 2023-04-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0011_delete_notifications_hospital_image'),
        ('userAccounts', '0013_remove_booking_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hospital',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='hospitalAccounts.hospital'),
            preserve_default=False,
        ),
    ]
