# Generated by Django 4.1.7 on 2023-03-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_position', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('muncipality', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('is_approved', models.CharField(default='Not Approved', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hospital', models.ManyToManyField(related_name='departments', to='hospitalAccounts.hospital')),
            ],
        ),
    ]
