# Generated by Django 4.1.7 on 2023-03-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
