# Generated by Django 4.1.7 on 2023-03-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0004_doctor_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='tokens',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
