# Generated by Django 4.1.7 on 2023-03-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0006_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='name',
            new_name='message',
        ),
    ]
