# Generated by Django 4.1.7 on 2023-03-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0007_rename_name_notifications_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
