# Generated by Django 4.1.7 on 2023-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0008_hospital_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
