# Generated by Django 4.1.7 on 2023-04-13 05:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0009_doctor_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
