# Generated by Django 4.1.7 on 2023-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0010_alter_doctor_tokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
